[tool.poetry]
name = "kursovaya4"
version = "0.1.0"
description = ""
authors = ["Denis Kirdyankin <kird.den@rambler.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
